FROM rockylinux:9

RUN dnf install -y epel-release; \
	dnf install -y cmake \
	libX11 \
	libX11-devel \
	libXrandr \
	libXrandr-devel \
	libXinerama \
	libXinerama-devel \
	fmt-devel \
	gcc \
	gcc-c++ \
	libXcursor \
	libXcursor-devel \
	ghc-OpenGL \
	ghc-OpenGL-devel \
	libXi \
	libXi-devel
